---
- name: update_upgrade
  apt: update_cache=yes upgrade=yes state=latest

- name: Install java7 
  apt: pkg=openjdk-7-jdk state=present update_cache=true

- name: Get Wowza
  get_url:
    url: {{ wowza_download_path }}/{{ wowza_file }}
    dest: /root/{{ wowza_file }}
    owner: root
    group: root
    mode: 0755

# Install expect (not expect-dev with dependencies)
- name: Install expect
  apt: name={{ item }} update_cache=yes
  with_items: the_expectables

- name: Push expect templates
  template:
    src: script.exp.j2
    dest: /root/script.exp
    owner: root
    group: root
    mode: 0755

- name: Run expect script, which runs Wowza installer
  args:
    creates: /usr/local/WowzaStreamingEngine/conf/Server.license
  shell: /root/script.exp

- name: Restart WowzaStreamingEngine
  service: name=WowzaStreamingEngine state=restarted

- name: Restart WowzaStreamingEngineManager
  service: name=WowzaStreamingEngineManager state=restarted

- name: Chmod /root/script.exp
  file:
    path: /root/script.exp
    owner: root
    group: root
    mode: 0400

- name: Chmod /root/{{ wowza_file }}
  file:
    path: /root/{{ wowza_file }}
    owner: root
    group: root
    mode: 0400
